### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by plattsad** [WarrenLab/agptools#7]
It looks like PIP installs this in a python 3.6 environment but maybe it requires a minimum python 3.7 environment?

(base) [agptools]$ agptools assemble ../../../txnsy2.bp.p_ctg.fa ../../ragtag_read-supported.scaffold.agp > ragtag_read-supported.scaffold.fasta
Traceback (most recent call last):
  File "/data/aplatts/miniconda2/bin/agptools", line 5, in <module>
    from agp.agptools import main
  File "/data/aplatts/miniconda2/lib/python3.6/site-packages/agp/agptools.py", line 5
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

**Comment by esrice** [comment]
pip never creates its own environment; it just installs the program in whatever environment you are currently in. It looks like you are in a conda environment that has python3.6 in it, so you can make a new one and install agptools in it like this:

```bash
conda create -n agptools python=3.8
conda activate agptools
pip install .
```

(of course you'll need to run the last command from the agptools directory)

All that being said, I should probably include an explicit requirement for python3.7+ in the installation files so that it just fails to install with an error message that says you need to update python, instead of installing but then not working with a cryptic error message like this. Thanks for pointing this out.

**Comment by plattsad** [comment]
Thanks, yup, I got it running fine in a conda environment with python 3.9, it just seemed like maybe the install script could check this.   (just saw that this is proposed - great).

**Comment by tillysscott** [comment]
Hello, just wanted to add another comment that creating a conda python 3.8 environment for agptools solved my installation problems. Thanks
